/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  javaSidebar: [{type: 'autogenerated', dirName: 'java'}],
  javaBasicSidebar: [{type: 'autogenerated', dirName: 'Java-basic'}],
  pythonSidebar: [{type: 'autogenerated', dirName: 'Python'}],
  jsSidebar: [{type: 'autogenerated', dirName: 'javascript'}],
  // mysqlSidebar: [{type: 'autogenerated', dirName: 'MySQL'}],
  // networkSidebar: [{type: 'autogenerated', dirName: 'Network'}],
  ccnaSidebar: [{type: 'autogenerated', dirName: 'CCNA'}],
  lpiSidebar: [{type: 'autogenerated', dirName: 'LPI'}],
  videoSidebar: [{type: 'autogenerated', dirName: 'Video'}],
  wsSidebar: [{type: 'autogenerated', dirName: 'WindowsServer'}],
  cmdSidebar: [{type: 'autogenerated', dirName: 'command'}],
  foundationSidebar: [{type: 'autogenerated', dirName: 'foundation'}],
  oracleSidebar: [{type: 'autogenerated', dirName: 'oracle'}],
  ws2Sidebar: [{type: 'autogenerated', dirName: 'ws'}],
  infraSidebar: [{type: 'autogenerated', dirName: 'infrastructure'}],
  awsSidebar: [{type: 'autogenerated', dirName: 'AWSSAA'}],
  c11nSidebar: [{type: 'autogenerated', dirName: 'nw-c11n'}],
  constxSidebar: [{type: 'autogenerated', dirName: 'constx'}],
  aisinSidebar: [{type: 'autogenerated', dirName: 'AI'}],
  // jsvSidebar: [{type: 'autogenerated', dirName: 'JavaScript'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
