/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  javaSidebar: [{type: 'autogenerated', dirName: 'java'}],
  pythonSidebar: [{type: 'autogenerated', dirName: 'Python'}],
  jsSidebar: [{type: 'autogenerated', dirName: 'javascript'}],
  // mysqlSidebar: [{type: 'autogenerated', dirName: 'MySQL'}],
  // networkSidebar: [{type: 'autogenerated', dirName: 'Network'}],
  ccnaSidebar: [{type: 'autogenerated', dirName: 'CCNA'}],
  lpiSidebar: [{type: 'autogenerated', dirName: 'LPI'}],
  videoSidebar: [{type: 'autogenerated', dirName: 'Video'}],
  foundationSidebar: [{type: 'autogenerated', dirName: 'foundation'}],
  // jsvSidebar: [{type: 'autogenerated', dirName: 'JavaScript'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
